name: Release and publish
on:
  push:
    branches:
      - fix/ci-avoid-unwanted-release
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: node
          target-branch: main
  test-true:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == true}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "one"
  test-false:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == false}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "two"
  test-true-str:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "one"
  test-false-str:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'false'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "two"
  test-json-true:
    needs: release-please
    if: ${{ fromJSON(needs.release-please.outputs.releases_created) == true}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "one json"
  test-json-false:
    needs: release-please
    if: ${{ fromJSON(needs.release-please.outputs.releases_created) == false}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "two json"
  test-json-true-str:
    needs: release-please
    if: ${{ fromJSON(needs.release-please.outputs.releases_created) == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "one json"
  test-json-false-str:
    needs: release-please
    if: ${{ fromJSON(needs.release-please.outputs.releases_created) == 'false'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "two json"
