name: docker
on:
  push:
    branches:
      - chore/setup-ci
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: get version
        id: get_version
        run: echo "package_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: leandredaumont/docker-web-recorder:latest,leandredaumont/docker-web-recorder:${{steps.get_version.outputs.package_version}}
