name: Lint
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          # By default, what is checked out is the merge commit (the branch + base branch), not the PR head
          # See: https://github.com/actions/checkout/issues/426
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Run lint command
        run: yarn run lint
